-- organizationId: required, and the default must never survive a write.
--
-- The column is NOT NULL. Prisma's generated types then demand organizationId
-- at every one of ~300 create sites, even though the scoped client supplies it
-- at runtime -- and writing it out by hand 300 times would defeat the point of
-- having a scoped client, with 300 chances to name the wrong organization.
--
-- So the column carries a default of '' purely so Prisma treats it as
-- optional in create inputs, and a CHECK constraint makes that default
-- impossible to actually store. A write that reaches the database without an
-- organization fails immediately and loudly, which is what we want: silence
-- here means a row nothing can protect.
ALTER TABLE "ActivityLog" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "AdSpendImport" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Alert" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "AlertRoutingRule" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Announcement" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "AnnouncementReaction" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "AppSetting" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ApplicantInviteToken" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ApplicantMessage" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "AvailabilityException" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Budget" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "BudgetCategory" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ChatConversation" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ChatMessage" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ChecklistTemplate" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ChecklistTemplateItem" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "CleanerStrike" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Client" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ClientAddress" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ClientCardSetupToken" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ClientPaymentMethod" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Commission" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Complaint" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Contact" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ContactActivity" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Document" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "DocumentAccessLog" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "DocumentSignature" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "DuplicateRejection" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "EmailLog" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "EmployeeAvailability" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "EmployeeFile" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "EmployeeProduct" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "EmployeeRating" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Faq" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "FaqCategory" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "FaqEvent" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "GiftCard" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "GroupChannel" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "GroupChannelMember" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "GroupChannelRead" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "GroupMessage" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryChange" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryCheckout" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryCheckoutItem" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryFlag" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryLocation" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryLocationStock" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InventoryRequest" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Invoice" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "InvoiceLineItem" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Job" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobAddOn" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobApplication" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobAssignment" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobAssignmentInvite" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobBreak" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobChatMessage" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobChecklist" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobChecklistItem" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobLog" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobPhoto" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobProductUsage" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobRatingToken" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "JobWorkSession" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "KitTemplate" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "KitTemplateItem" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "LandingPage" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Lead" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "MarketingCampaign" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "NotificationSetting" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "PageVisit" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "PayPeriod" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Payout" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "PricingRule" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Product" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ProductLink" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "PromoCode" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "PropertyDefinition" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "QuoteRequest" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "RagWash" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "RecurringCancellation" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ReviewPhoto" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "SalesArea" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "ServiceArea" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Supplier" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "SupplierPrice" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Target" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "TrainingModule" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "TrainingProgress" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "TrainingQuiz" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Transaction" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "User" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Waitlist" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "WashPayout" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "WebhookEvent" ALTER COLUMN "organizationId" SET DEFAULT '';
ALTER TABLE "Withdrawal" ALTER COLUMN "organizationId" SET DEFAULT '';

ALTER TABLE "ActivityLog" ADD CONSTRAINT "ActivityLog_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "AdSpendImport" ADD CONSTRAINT "AdSpendImport_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "AlertRoutingRule" ADD CONSTRAINT "AlertRoutingRule_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "AnnouncementReaction" ADD CONSTRAINT "AnnouncementReaction_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "AppSetting" ADD CONSTRAINT "AppSetting_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ApplicantInviteToken" ADD CONSTRAINT "ApplicantInviteToken_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ApplicantMessage" ADD CONSTRAINT "ApplicantMessage_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "AvailabilityException" ADD CONSTRAINT "AvailabilityException_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Budget" ADD CONSTRAINT "Budget_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "BudgetCategory" ADD CONSTRAINT "BudgetCategory_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ChatConversation" ADD CONSTRAINT "ChatConversation_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ChecklistTemplate" ADD CONSTRAINT "ChecklistTemplate_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ChecklistTemplateItem" ADD CONSTRAINT "ChecklistTemplateItem_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "CleanerStrike" ADD CONSTRAINT "CleanerStrike_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Client" ADD CONSTRAINT "Client_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ClientAddress" ADD CONSTRAINT "ClientAddress_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ClientCardSetupToken" ADD CONSTRAINT "ClientCardSetupToken_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ClientPaymentMethod" ADD CONSTRAINT "ClientPaymentMethod_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Commission" ADD CONSTRAINT "Commission_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Complaint" ADD CONSTRAINT "Complaint_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ContactActivity" ADD CONSTRAINT "ContactActivity_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Document" ADD CONSTRAINT "Document_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "DocumentAccessLog" ADD CONSTRAINT "DocumentAccessLog_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "DocumentSignature" ADD CONSTRAINT "DocumentSignature_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "DuplicateRejection" ADD CONSTRAINT "DuplicateRejection_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "EmailLog" ADD CONSTRAINT "EmailLog_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "EmployeeAvailability" ADD CONSTRAINT "EmployeeAvailability_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "EmployeeFile" ADD CONSTRAINT "EmployeeFile_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "EmployeeProduct" ADD CONSTRAINT "EmployeeProduct_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "EmployeeRating" ADD CONSTRAINT "EmployeeRating_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Faq" ADD CONSTRAINT "Faq_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "FaqCategory" ADD CONSTRAINT "FaqCategory_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "FaqEvent" ADD CONSTRAINT "FaqEvent_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "GiftCard" ADD CONSTRAINT "GiftCard_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "GroupChannel" ADD CONSTRAINT "GroupChannel_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "GroupChannelMember" ADD CONSTRAINT "GroupChannelMember_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "GroupChannelRead" ADD CONSTRAINT "GroupChannelRead_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "GroupMessage" ADD CONSTRAINT "GroupMessage_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryChange" ADD CONSTRAINT "InventoryChange_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryCheckout" ADD CONSTRAINT "InventoryCheckout_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryCheckoutItem" ADD CONSTRAINT "InventoryCheckoutItem_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryFlag" ADD CONSTRAINT "InventoryFlag_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryLocation" ADD CONSTRAINT "InventoryLocation_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryLocationStock" ADD CONSTRAINT "InventoryLocationStock_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InventoryRequest" ADD CONSTRAINT "InventoryRequest_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Job" ADD CONSTRAINT "Job_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobAddOn" ADD CONSTRAINT "JobAddOn_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobApplication" ADD CONSTRAINT "JobApplication_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobAssignment" ADD CONSTRAINT "JobAssignment_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobAssignmentInvite" ADD CONSTRAINT "JobAssignmentInvite_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobBreak" ADD CONSTRAINT "JobBreak_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobChatMessage" ADD CONSTRAINT "JobChatMessage_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobChecklist" ADD CONSTRAINT "JobChecklist_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobChecklistItem" ADD CONSTRAINT "JobChecklistItem_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobLog" ADD CONSTRAINT "JobLog_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobPhoto" ADD CONSTRAINT "JobPhoto_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobProductUsage" ADD CONSTRAINT "JobProductUsage_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobRatingToken" ADD CONSTRAINT "JobRatingToken_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "JobWorkSession" ADD CONSTRAINT "JobWorkSession_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "KitTemplate" ADD CONSTRAINT "KitTemplate_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "KitTemplateItem" ADD CONSTRAINT "KitTemplateItem_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "LandingPage" ADD CONSTRAINT "LandingPage_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "MarketingCampaign" ADD CONSTRAINT "MarketingCampaign_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "NotificationSetting" ADD CONSTRAINT "NotificationSetting_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "PageVisit" ADD CONSTRAINT "PageVisit_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "PayPeriod" ADD CONSTRAINT "PayPeriod_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "PricingRule" ADD CONSTRAINT "PricingRule_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Product" ADD CONSTRAINT "Product_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ProductLink" ADD CONSTRAINT "ProductLink_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "PromoCode" ADD CONSTRAINT "PromoCode_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "PropertyDefinition" ADD CONSTRAINT "PropertyDefinition_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "QuoteRequest" ADD CONSTRAINT "QuoteRequest_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "RagWash" ADD CONSTRAINT "RagWash_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "RecurringCancellation" ADD CONSTRAINT "RecurringCancellation_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ReviewPhoto" ADD CONSTRAINT "ReviewPhoto_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "SalesArea" ADD CONSTRAINT "SalesArea_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "ServiceArea" ADD CONSTRAINT "ServiceArea_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "SupplierPrice" ADD CONSTRAINT "SupplierPrice_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Target" ADD CONSTRAINT "Target_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "TrainingModule" ADD CONSTRAINT "TrainingModule_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "TrainingProgress" ADD CONSTRAINT "TrainingProgress_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "TrainingQuiz" ADD CONSTRAINT "TrainingQuiz_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "User" ADD CONSTRAINT "User_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Waitlist" ADD CONSTRAINT "Waitlist_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "WashPayout" ADD CONSTRAINT "WashPayout_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "WebhookEvent" ADD CONSTRAINT "WebhookEvent_organizationId_not_blank" CHECK ("organizationId" <> '');
ALTER TABLE "Withdrawal" ADD CONSTRAINT "Withdrawal_organizationId_not_blank" CHECK ("organizationId" <> '');
